### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ggnimade** [aesuli/amadown2py#1]
Hi, Andrea,
Thanks for your work. This is very helpful.

After I crawled the data and ran amazon_parser.py, I got the following error:

`D:\>amr\amazon_parser.py -d reviews -o reviews.csv
(u'B01DSNOBPK', 'reviews\\de\\B01DSNOBPK\\B01DSNOBPK_1.html')
Traceback (most recent call last):
  File "D:\amr\amazon_parser.py", line 98, in <module>
    main()
  File "D:\amr\amazon_parser.py", line 63, in main
    htmlpage = contentre.findall(htmlpage)[0]
IndexError: list index out of range`

I know little about Python. It would be great if you can help. Thanks.

**Comment by aesuli** [comment]
It seems that review pages for items with only one page of reviews do not match the regex used to isolate the reviews section of the page. I'm working on fixing it.

**Comment by aesuli** [comment]
I tested on the same product id and domain of your example and now it works. Please confirm, and eventually close this issue.

**Comment by ggnimade** [comment]
Thanks, Andrea. The amended version works great.

**Comment by ggnimade** [comment]
Hi, Andrea. I reopened this case since I found the error still exists. After many times' trying and checking, I found that when there's no review under that ASIN, the IndexError will happen. For example, B0132M8H0W at .de site. Could you please help to fix it? Thanks a lot.

**Comment by aesuli** [comment]
Added a check for it.

**Comment by ggnimade** [comment]
It works perfectly now. Thanks.
